#! /bin/sh
### BEGIN INIT INFO
# Provides: techblog.co.il
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: hass
# Description: This file starts and stops Home-assistant
# this script is for ubuntu 14.04 
### END INIT INFO

TOMCAT_DIR=/home/joe/programs/apache-tomcat-8.0.5/
export JAVA_HOME=/home/joe/programs/jdk1.8.0_05

case "$1" in
 start)
   echo "starting hass ui"
   hass --open-ui
   ;;
 stop)
   echo "stoping hass ui"
   killall -9 hass
   sleep 10
   ;;
 restart)
   echo "stoping hass ui"
   killall -9 hass
   sleep 20
   echo "starting hass ui"
   hass --open-ui
   ;;
 *)
   echo "Usage: tomcat {start|stop|restart}" >&2
   exit 3
   ;;
esac
